"""Create menu_items table

Revision ID: f8242b58fbb7
Revises: 
Create Date: 2025-11-14 20:10:15.997849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8242b58fbb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('serving_size', sa.Text(), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fiber_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dining_hall', sa.Text(), nullable=True),
    sa.Column('service', sa.Text(), nullable=True),
    sa.Column('dates_seen', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_dining_hall'), 'menu_items', ['dining_hall'], unique=False)
    op.create_index(op.f('ix_menu_items_name'), 'menu_items', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_items_name'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_dining_hall'), table_name='menu_items')
    op.drop_table('menu_items')
    # ### end Alembic commands ###

